# Separate from pr.yml for the badge in readme.md
# The name 'Build' is used by the same badge to generate a SVG
name: Build
on:
  push:

concurrency: 
  group: onpush
  cancel-in-progress: true

jobs:
  debug:
    uses: security-code-scan/security-code-scan/.github/workflows/build.yml@vs2019
    with:
      configuration: Debug
  release:
    uses: security-code-scan/security-code-scan/.github/workflows/build.yml@vs2019
    with:
      configuration: Release
