# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: DotnetariumSCS.sln
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.1xx

    - name: Build with dotnet
      run: dotnet build --configuration Release .\DotnetariumSCS\DotnetariumSCS.csproj
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        retention-days: 7
        name: packages
        path: |
          ./DotnetariumSCS/bin/Release/**/*.nupkg
      
  